FROM nvcr.io/nvidia/dli/dli-nano-ai:v2.0.2-r32.7.1

RUN rm -rf /nvdli-nano/classification
RUN rm -rf /nvdli-nano/hello_camera
RUN rm -rf /nvdli-nano/images
RUN rm -rf /nvdli-nano/info.md
RUN rm -rf /nvdli-nano/regression
RUN wget -O /nvdli-nano/take-photo.ipynb https://raw.githubusercontent.com/integemjack/tf-online/main/take-photo.ipynb
